name: Deploy Summit AI to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --region=global \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/summit-ai \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --verbosity=debug

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy summit-ai \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/summit-ai \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}
